import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── 99acres brand ──────────────────────────────────────────────────
        brand: {
          red:        '#d9232d',
          'red-dark': '#b71c24',
          orange:     '#f47920',
          yellow:     '#f5a623',
        },
        // ── Design tokens (primary → brand red) ────────────────────────────
        'primary':                  '#d9232d',
        'primary-container':        '#b71c24',
        'primary-fixed':            '#fce4e5',
        'primary-fixed-dim':        '#f4a0a3',
        'inverse-primary':          '#f4a0a3',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#ffffff',
        'on-primary-fixed':         '#3a0008',
        'on-primary-fixed-variant': '#7a0012',
        'surface-tint':             '#d9232d',
        // ── Surfaces & backgrounds ─────────────────────────────────────────
        'surface-bright':           '#f7f7f7',
        'surface':                  '#f7f7f7',
        'background':               '#f7f7f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f2f2f2',
        'surface-container':        '#ebebeb',
        'surface-container-high':   '#e2e2e2',
        'surface-container-highest':'#d9d9d9',
        'surface-variant':          '#e8e8e8',
        'surface-dim':              '#d4d4d4',
        'inverse-surface':          '#2a2a2a',
        'inverse-on-surface':       '#f5f5f5',
        // ── Text & outline ─────────────────────────────────────────────────
        'on-surface':               '#212121',
        'on-surface-variant':       '#666666',
        'on-background':            '#212121',
        'outline':                  '#999999',
        'outline-variant':          '#e0e0e0',
        // ── Secondary (keep purple accent for badges) ──────────────────────
        'secondary':                '#a700ad',
        'secondary-container':      '#ff66ff',
        'secondary-fixed':          '#ffd6f7',
        'secondary-fixed-dim':      '#ffaaf7',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#6d0071',
        'on-secondary-fixed':       '#37003a',
        'on-secondary-fixed-variant':'#800084',
        // ── Tertiary ───────────────────────────────────────────────────────
        'tertiary':                 '#5a5c5e',
        'tertiary-container':       '#737577',
        'tertiary-fixed':           '#e1e2e4',
        'tertiary-fixed-dim':       '#c5c6c8',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#fcfcfe',
        'on-tertiary-fixed':        '#191c1e',
        'on-tertiary-fixed-variant':'#444749',
        // ── Error ──────────────────────────────────────────────────────────
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
      },
      fontSize: {
        'h1':            ['2.5rem',  { lineHeight: '1.2', fontWeight: '800' }],
        'h2':            ['1.75rem', { lineHeight: '1.3', fontWeight: '700' }],
        'h3':            ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'price-display': ['1.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg':       ['1rem',    { lineHeight: '1.6' }],
        'body-md':       ['0.875rem',{ lineHeight: '1.5' }],
        'body-sm':       ['0.75rem', { lineHeight: '1.5' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:     '0.5rem',
        xl:     '0.75rem',
        full:   '9999px',
      },
      spacing: {
        xs:             '4px',
        sm:             '8px',
        md:             '16px',
        lg:             '24px',
        xl:             '48px',
        base:           '4px',
        gutter:         '20px',
        'container-max':'1200px',
      },
      fontFamily: {
        manrope:       ['Manrope', 'sans-serif'],
        'h1':          ['Manrope', 'sans-serif'],
        'h2':          ['Manrope', 'sans-serif'],
        'h3':          ['Manrope', 'sans-serif'],
        'price-display':['Manrope', 'sans-serif'],
        'label-bold':  ['Inter', 'sans-serif'],
        'body-lg':     ['Inter', 'sans-serif'],
        'body-md':     ['Inter', 'sans-serif'],
        'body-sm':     ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
} satisfies Config;
