import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f6f9ff',
        'primary-fixed': '#d4e3ff',
        'on-tertiary-container': '#fcfcfe',
        'on-secondary-fixed': '#37003a',
        'surface': '#f6f9ff',
        'tertiary': '#5a5c5e',
        'on-tertiary-fixed': '#191c1e',
        'primary-fixed-dim': '#a5c8ff',
        'inverse-surface': '#2a3138',
        'on-primary-fixed': '#001c3a',
        'on-primary-container': '#fefcff',
        'error': '#ba1a1a',
        'tertiary-container': '#737577',
        'secondary-container': '#ff66ff',
        'surface-tint': '#005faf',
        'on-background': '#151c22',
        'background': '#f6f9ff',
        'tertiary-fixed-dim': '#c5c6c8',
        'surface-container-low': '#edf4fd',
        'inverse-primary': '#a5c8ff',
        'on-secondary-container': '#6d0071',
        'secondary': '#a700ad',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#414753',
        'on-surface': '#151c22',
        'primary-container': '#0075d6',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e2e9f1',
        'secondary-fixed': '#ffd6f7',
        'on-error-container': '#93000a',
        'primary': '#005cab',
        'outline': '#717784',
        'on-primary-fixed-variant': '#004786',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-highest': '#dce3ec',
        'on-secondary-fixed-variant': '#800084',
        'surface-container': '#e8eff7',
        'inverse-on-surface': '#ebf1fa',
        'outline-variant': '#c0c7d5',
        'surface-variant': '#dce3ec',
        'secondary-fixed-dim': '#ffaaf7',
        'on-tertiary-fixed-variant': '#444749',
        'tertiary-fixed': '#e1e2e4',
        'surface-dim': '#d4dbe3',
      },
      fontSize: {
        'h1':            ['2.5rem',  { lineHeight: '1.2', fontWeight: '800' }],
        'h2':            ['1.75rem', { lineHeight: '1.3', fontWeight: '700' }],
        'h3':            ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'price-display': ['1.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg':       ['1rem',    { lineHeight: '1.6' }],
        'body-md':       ['0.875rem',{ lineHeight: '1.5' }],
        'body-sm':       ['0.75rem', { lineHeight: '1.5' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:     '0.5rem',
        xl:     '0.75rem',
        full:   '9999px',
      },
      spacing: {
        xs:             '4px',
        sm:             '8px',
        md:             '16px',
        lg:             '24px',
        xl:             '48px',
        base:           '4px',
        gutter:         '20px',
        'container-max':'1200px',
      },
      fontFamily: {
        manrope:       ['Manrope', 'sans-serif'],
        'h1':          ['Manrope', 'sans-serif'],
        'h2':          ['Manrope', 'sans-serif'],
        'h3':          ['Manrope', 'sans-serif'],
        'price-display':['Manrope', 'sans-serif'],
        'label-bold':  ['Inter', 'sans-serif'],
        'body-lg':     ['Inter', 'sans-serif'],
        'body-md':     ['Inter', 'sans-serif'],
        'body-sm':     ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
} satisfies Config;
